# Generated by Django 4.2.3 on 2023-07-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('user_id', models.IntegerField()),
                ('blog_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_draft', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LikeModel',
            fields=[
                ('user_id', models.IntegerField()),
                ('blog_id', models.IntegerField()),
                ('like_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
